# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Our Research, Ourselves
tagline:          'A duoethnography on mentoring and researcher identity'
description:      'A duoethnography on mentoring and researcher identity.'
url:
baseurl:          /templatepractice

author:
  name:           'Will Chesher'
  url:



# Custom vars
version:          2.1.0

github:
  repo:
