# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Our Research, Ourselves
tagline:          'A duoethnography on mentoring and researcher identity'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:
baseurl:          /templatepractice

author:
  name:           'Will Chesher'
  url:



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
